### ISSUE TITLE
Compliance plugin causes blank pages

### ISSUE THREAD

**Issue by vivid-pixel** [joshp23/YOURLS-Compliance#12]
`[31-Aug-2018 18:38:56 UTC] PHP Fatal error:  Call to undefined method ezSQL_pdo_YOURLS::fetchOne() in /home/xyz/public_html/user/plugins/compliance/plugin.php on line 317`

The first sign that there's an issue was when you activate the plugin, you get a blank screen. From there on, every time you submit a URL to shorten, you get back to a blank screen as well. And the admin page fails to display any short URLs though still renders correctly minus the missing data.

YOURLS version: 1.7.2

Plugins I have activated:
- Anti spam 1.0.4 
- Change error messages 1.2.1
- HTTP:BL 2.0.5
- Preview URL 1.0
- Random Keywords 1.1
- Sleeky Backend 2.0

**Comment by joshp23** [comment]
The big clue is the ezSQL_pdo stuff. I updated this to work with YOURLS 1.7.3... I would get an earlier release or wait for me to make it backwards compatible.

**Comment by joshp23** [comment]
1.3.0 of this plugin was the last release before I updared fir YOURLS 1.7.3... So either downgrade that or upgrade YOURLS from git master. Sorry for the hiccup.

**Comment by vivid-pixel** [comment]
Oh, that makes sense then. Well now I know what to do, so thank you!

**Comment by joshp23** [comment]
I'll update here when backwards compatibility is added. Won't be long.

**Comment by joshp23** [comment]
latest release addresses this. Backwards compatibility added with 1.4.0

**Comment by joshp23** [comment]
please note: http:BL needs the same backwards compatibility fix, expect that soon. If this is not an issue, please update that plugin now to the latest release (2.0.6) for a critical error fix.
